// build.js
const fs = require('fs');
const path = require('path');

const url = process.env.APPS_SCRIPT_URL;

if (!url) {
    console.error('Error: APPS_SCRIPT_URL environment variable is not set.');
    process.exit(1);
}

const content = `// This file is auto-generated by build.js
export const APPS_SCRIPT_URL = '${url}';
`;

// Ensure the js directory exists
const jsDir = path.join(__dirname, 'js');
if (!fs.existsSync(jsDir)) {
    fs.mkdirSync(jsDir);
}

fs.writeFileSync(path.join(jsDir, 'env.js'), content, 'utf8');

console.log('Successfully wrote APPS_SCRIPT_URL to js/env.js');
